# Generated by Django 2.0.4 on 2018-05-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_tarih', models.DateTimeField(blank=True, null=True)),
                ('aciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hastane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastane_adi', models.CharField(max_length=100)),
                ('eposta', models.EmailField(default='asdsad@asdasd.com', max_length=50)),
                ('sifre', models.CharField(default='1sa1', max_length=50)),
                ('oneri', models.CharField(default='Onerinizi giriniz.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il_adi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=30)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il')),
            ],
        ),
        migrations.CreateModel(
            name='KanGrubu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KanGrubu_adi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyad', models.CharField(max_length=20)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('cinsiyet', models.NullBooleanField(choices=[(True, 'Erkek'), (False, 'Kadın')])),
                ('telefon', models.CharField(max_length=11)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Ilce')),
                ('kanGrubu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.KanGrubu')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_adi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stokMiktari', models.IntegerField(default=0)),
                ('hastane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Hastane')),
                ('kanGrubu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.KanGrubu')),
            ],
        ),
        migrations.AddField(
            model_name='kullanici',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Rol'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hastane',
            name='il',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il'),
        ),
        migrations.AddField(
            model_name='hastane',
            name='ilce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Ilce'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ilce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Ilce'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kanGrubu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.KanGrubu'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
