# Generated by Django 2.0.4 on 2018-05-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0002_auto_20180507_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol_adi',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
