# Generated by Django 2.0.4 on 2018-04-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0003_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=30)),
                ('il_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il')),
            ],
        ),
    ]
