# Generated by Django 2.0.4 on 2018-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0003_auto_20180508_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol_adi',
            field=models.CharField(default=1, max_length=20, null=True),
        ),
    ]
