# Generated by Django 2.0.4 on 2018-05-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0004_auto_20180508_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='rol',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Rol'),
        ),
    ]
