# Generated by Django 2.0.4 on 2018-05-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0005_auto_20180508_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_adi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
