# Generated by Django 2.0.4 on 2018-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0008_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stokMiktari', models.IntegerField(default=0)),
                ('hastane_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Hastane')),
                ('kanGrubu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.KanGrubu')),
            ],
        ),
    ]
