# Generated by Django 2.0.4 on 2018-04-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanBankasiApp', '0009_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_tarih', models.DateTimeField(blank=True, null=True)),
                ('aciklama', models.TextField()),
                ('il_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Il')),
                ('ilce_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.Ilce')),
                ('kanGrubu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanBankasiApp.KanGrubu')),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
