# Generated by Django 2.0.4 on 2018-04-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanBankasiApp', '0010_duyuru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyuru',
            old_name='il_id',
            new_name='il',
        ),
        migrations.RenameField(
            model_name='duyuru',
            old_name='ilce_id',
            new_name='ilce',
        ),
        migrations.RenameField(
            model_name='duyuru',
            old_name='kanGrubu_id',
            new_name='kanGrubu',
        ),
        migrations.RenameField(
            model_name='duyuru',
            old_name='kullanici_id',
            new_name='kullanici',
        ),
        migrations.RenameField(
            model_name='hastane',
            old_name='ilce_id',
            new_name='ilce',
        ),
        migrations.RenameField(
            model_name='ilce',
            old_name='il_id',
            new_name='il',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='il_id',
            new_name='il',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='ilce_id',
            new_name='ilce',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='kanGrubu_id',
            new_name='kanGrubu',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='rol_id',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='hastane_id',
            new_name='hastane',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='kanGrubu_id',
            new_name='kanGrubu',
        ),
    ]
